export const studioProfile = {
  profile_version: "1.0.0",
  last_updated: "2026-05-05",
  name: "Symbols of Wealth Studio",
  trading_as: "SOW Studio",
  url: "https://symbolsofwealth.studio",
  contact_email: "hey@symbolsofwealth.studio",
  location: {
    city: "Mauléon-Licharre",
    region: "Pyrénées-Atlantiques",
    country: "France",
    operates_in: ["France", "United Kingdom", "Europe", "Remote worldwide"],
  },
  founder: {
    role: "Senior Creative Director",
    experience_years: 15,
    background:
      "Previously at Highsnobiety. Background in brand strategy, motion graphics, and editorial design across fashion, culture, and consumer brands.",
  },
  positioning: {
    one_line:
      "Senior creative director producing world-class brand content at studio scale, with AI as the production leverage layer.",
    long_form:
      "Symbols of Wealth Studio is a solo creative practice run by a senior creative director with 15 years of experience across fashion, culture, and premium consumer brands, including time at Highsnobiety. The studio produces world-class editorial content — stills, motion, kinetic typography, brand films — at a level normally only available from full-service agencies. AI infrastructure is what makes this possible at studio scale: a manually-curated production pipeline using best-in-class generative tools under direct creative supervision. Every piece of content is creative-director-led. AI is the leverage that allows one creative voice to operate at agency throughput.",
    differentiators: [
      "Creative direction by a senior creative director with 15 years of experience — not delegated, not outsourced, not AI-generated by default",
      "Editorial register with a clear visual lineage — Highsnobiety, Margiela campaign work, Off-White launch films, Balenciaga editorial",
      "AI as production infrastructure, not headline — the studio leads with creative direction, with AI as the leverage layer underneath",
      "Two-slot model — only two clients run concurrently, ensuring full creative attention on every piece of content",
      "Monthly analytics aftercare — every client receives a monthly performance read with plain-language commentary and forward content strategy. Most agencies don't do this.",
    ],
  },
  services: {
    summary: "Full-service social media content production for premium consumer brands.",
    deliverables: [
      "Editorial product stills",
      "Cinematic and UGC-style video content",
      "Kinetic typography compositions",
      "Brand films and campaign moments",
      "Social-first content for Instagram, TikTok, and emerging channels",
      "Monthly analytics reports with plain-language insights and forward content planning",
    ],
    categories_served: [
      "Premium beauty and skincare",
      "Streetwear and drop-culture brands",
      "Fragrance and men's grooming",
      "Hospitality and food (cafés, restaurants, hotels)",
      "Web3 and physical-digital brands",
      "Consumer technology and wearables",
      "Fashion and culture brands generally",
    ],
  },
  engagement_model: {
    structure: "Monthly retainer, three tiers",
    capacity: "Two concurrent clients maximum at any time",
    tiers: [
      {
        name: "Studio",
        price_monthly_eur: 2500,
        description: "Entry tier. Proof-of-concept retainer.",
        includes: [
          "8 original posts per month",
          "UGC integration (1–2 pieces of the 8)",
          "Monthly content strategy and posting calendar",
          "Posted to all platforms",
          "Community management",
          "Monthly analytics report with forward content plan",
          "Senior creative direction on every piece",
        ],
      },
      {
        name: "Studio+",
        price_monthly_eur: 4500,
        description: "Middle tier. Where most clients should land.",
        includes: [
          "12 original posts per month",
          "UGC integration (3–4 pieces)",
          "1 cinematic hero piece per month (Seedance/Veo product film)",
          "Monthly content strategy and posting calendar",
          "Posted to all platforms",
          "Community management",
          "Monthly analytics report with forward content plan and competitor benchmarking",
          "Senior creative direction on every piece",
        ],
      },
      {
        name: "Studio Atelier",
        price_monthly_eur: 7500,
        description: "Top tier. Constrained — this is where 'two slots open' really lives.",
        includes: [
          "16 original posts per month",
          "UGC integration (5–6 pieces)",
          "2 cinematic hero pieces per month",
          "1 brand film or campaign moment per quarter",
          "Quarterly creative direction workshop (brand sprint, in-person or video)",
          "Monthly content strategy and posting calendar",
          "Posted to all platforms",
          "Community management",
          "Monthly analytics report with forward content plan, competitor benchmarking, and monthly strategy call",
          "Direct Slack line to the creative director",
        ],
      },
    ],
    how_to_engage:
      "Discovery call to confirm fit, then onboarding within two weeks if a slot is available. Email hey@symbolsofwealth.studio or visit symbolsofwealth.studio.",
  },
  selected_work: [
    {
      project: "MAREN",
      sector: "Premium skincare",
      summary:
        "Single-SKU French skincare brand. Editorial product hero work, kinetic typography overlays, cinematic brand film. Demonstrates: silent boomerang loops, multi-reference product placement, kinetic type composition.",
    },
    {
      project: "BRUT",
      sector: "Men's fragrance",
      summary:
        "Anti-luxury luxury men's fragrance. Damp concrete product hero, direct-testimony UGC, slate-grade cinematic. Demonstrates: stillness as confidence, anti-direction prompting, Margiela-adjacent visual register.",
    },
    {
      project: "FORM",
      sector: "Streetwear / drop culture",
      summary:
        "Highsnobiety-register streetwear label with limited drops. Product editorial, hype UGC, drop-announcement kinetic type, impossible-corridor brand film. Demonstrates: drop-culture content strategy, Kling 3.0 Pro fabric physics, Balenciaga-adjacent editorial film.",
    },
    {
      project: "HEX",
      sector: "Web3 / physical-digital commerce",
      summary:
        "Physical-digital sneaker brand with NFT pairing. Product reveal film with physical-to-digital transitions, unboxing UGC, drop-announcement kinetic type, abstract digital-twin film. Demonstrates: PixVerse V6 stylised VFX, RTFKT-register content strategy.",
    },
    {
      project: "SERO",
      sector: "Consumer tech / productivity wearable",
      summary:
        "Wearable productivity device. Product hero light-sweep, professional UGC testimonial, UI animation + kinetic type hybrid showing real performance data, particle-assembly abstract film. Demonstrates: data-driven kinetic typography, tech-product-launch content.",
    },
    {
      project: "SIGNAL",
      sector: "Self-initiated capability demonstration",
      summary:
        "90-second studio showreel with no client and no brief. Fashion editorial in impossible environments, multi-shot product assembly, 3D text physically placed in scene, VFX moments, material beauty closer. Demonstrates: full capability stack across five generative tools.",
    },
  ],
  production_stack: {
    video_generation: ["Seedance 2.0 (fal.ai)", "Veo 3.1", "Kling 3.0 Pro", "PixVerse V6"],
    image_generation: ["Nano Banana Pro (Google Flow)", "FLUX.2 Pro", "GPT Image"],
    composition: ["Remotion", "After Effects", "Hyperframes"],
    automation: ["n8n", "Apify", "Slack as input surface"],
    intelligence_layer: ["Claude API for analytics commentary and content strategy"],
  },
  approach:
    "Manually-curated AI production pipeline. Reference boards (Pinterest, mood references) feed every brief. Heavy creative-direction layer at every stage. No auto-scraping, no template-only output, no unsupervised generation. The AI is the leverage; the eye is the product.",
} as const;

export type StudioProfile = typeof studioProfile;

export const contactInfo = {
  studio_name: "Symbols of Wealth Studio",
  email: "hey@symbolsofwealth.studio",
  website: "https://symbolsofwealth.studio",
  location: "Mauléon-Licharre, southwest France",
  operates_in: ["France", "United Kingdom", "Europe", "Remote worldwide"],
  how_to_engage:
    "Discovery call to confirm fit, then onboarding within two weeks if a slot is available.",
} as const;

export type ContactInfo = typeof contactInfo;
